spring:
  profiles:
    active: sqg
  swagger:
    base-package: dockerproj.dkject
    enabled: true
    title: dk在线文档
    description: 做个小测试吧
    version: 1.0.1
    contact:
      name: 孙琼纲
      url: https://www.cnblogs.com/sansyou/
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123456
    timeout: 11110
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: -1
        max-active: 8
  thymeleaf:
    cache: false
server:
  port: 8088
logging:
  #level:
    #root: ERROR
    #"dockerproj.dkject.sqg": INFO
  ##输出到文件夹 d:\\log
  path: d:\\log
  ##输出到文件 d:\\log2\\my.log
  file: d:\\log2\\my.log