my:
  name: sqg
  age: 27
  active: sqg
  sex: m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sun123456
    url: jdbc:mysql://localhost:3306/graphql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
